// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR4eZ7e9FcSg-Gpj9RmcdgcRufOuWl_50',
    appId: '1:56106440521:web:62eeff74d33e209c552c98',
    messagingSenderId: '56106440521',
    projectId: 'movegui-253e0',
    authDomain: 'movegui-253e0.firebaseapp.com',
    storageBucket: 'movegui-253e0.firebasestorage.app',
    measurementId: 'G-9V3MYETS03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4on4jCFeDqA4xOYU2sh0HfXiB0s5qakc',
    appId: '1:56106440521:android:7e122a62af3e531a552c98',
    messagingSenderId: '56106440521',
    projectId: 'movegui-253e0',
    storageBucket: 'movegui-253e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf15rDhgNij9yhbFVNydNlFV1mHDF_djI',
    appId: '1:56106440521:ios:6d208ff6ea392a9e552c98',
    messagingSenderId: '56106440521',
    projectId: 'movegui-253e0',
    storageBucket: 'movegui-253e0.firebasestorage.app',
    androidClientId: '56106440521-bpfu8o0n0ltrpfko17e9gmju0rn79bft.apps.googleusercontent.com',
    iosClientId: '56106440521-i9o5mnc2ii6k1ourc3h5tkqh4mbdrce6.apps.googleusercontent.com',
    iosBundleId: 'com.example.movegui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf15rDhgNij9yhbFVNydNlFV1mHDF_djI',
    appId: '1:56106440521:ios:6d208ff6ea392a9e552c98',
    messagingSenderId: '56106440521',
    projectId: 'movegui-253e0',
    storageBucket: 'movegui-253e0.firebasestorage.app',
    androidClientId: '56106440521-bpfu8o0n0ltrpfko17e9gmju0rn79bft.apps.googleusercontent.com',
    iosClientId: '56106440521-i9o5mnc2ii6k1ourc3h5tkqh4mbdrce6.apps.googleusercontent.com',
    iosBundleId: 'com.example.movegui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR4eZ7e9FcSg-Gpj9RmcdgcRufOuWl_50',
    appId: '1:56106440521:web:a402222325e9669d552c98',
    messagingSenderId: '56106440521',
    projectId: 'movegui-253e0',
    authDomain: 'movegui-253e0.firebaseapp.com',
    storageBucket: 'movegui-253e0.firebasestorage.app',
    measurementId: 'G-FC21FJQ40Y',
  );
}
